opt_in_rules:
  - force_unwrapping

disabled_rules:
  - line_length

included:
  - Sources
  - Tests

identifier_name:
  excluded:
    - 🐢
    - 🐇
    - x
    - y
    - r
    - g
    - b

force_cast: warning

large_tuple: 
  warning: 3
  error: 4